oras digest extract

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,6 +5,7 @@ on:
     branches:
       - main
       - release
+      - fix/gh-actions
     tags:
       - "beta-v*"
   pull_request:
@@ -69,20 +70,20 @@ jobs:
         run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
 
       - name: Login to GitHub Container Registry
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: |
           echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{github.repository_owner}} --password-stdin
 
       - name: Install Cosign
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         uses: sigstore/cosign-installer@main
 
       - name: Check install!
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: cosign version
 
       - name: place the cosign private key in a file
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: 'echo "$COSIGN_KEY" > /tmp/cosign.key'
         shell: bash
         env:
@@ -107,33 +108,38 @@ jobs:
         with:
           sbom-artifact-match: ".*\\.cyclonedx$"
       - name: Remove older SBOMs
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: rm -rf sbom*.* || true
       - name: Download artifact for SPDX Report
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         uses: actions/download-artifact@v3
         with:
           name: sbom.spdx
       - name: Download artifact for CycloneDx Report
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         uses: actions/download-artifact@v3
         with:
           name: sbom.cyclonedx
       - name: ORAS Setup & Push SBOM reports to GitHub Container Registry
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: |
           ORAS_VERSION="v0.8.1"
           ORAS_FILENAME="oras_0.8.1_linux_amd64.tar.gz"
           curl -LO "https://github.com/oras-project/oras/releases/download/${ORAS_VERSION}/${ORAS_FILENAME}"
           mkdir oras_install
           tar -xvf "${ORAS_FILENAME}" -C oras_install
-          ./oras_install/oras push ghcr.io/${{github.repository_owner}}/logs-viewer/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*
+          result=$(./oras_install/oras push ghcr.io/${{github.repository_owner}}/logs-viewer/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }} ./*sbom.*)
+          echo "::set-env name=ORAS_DIGEST::$(echo $result | grep -oE '[a-f0-9]{64}')"
+          if [ -z "$ORAS_DIGEST" ]; then
+            echo "Error: ORAS_DIGEST is empty"
+            exit 1
+          fi
           cd ..
 
       - name: Sign the sbom images
-        if: github.ref == 'refs/heads/release'
+        #if: github.ref == 'refs/heads/release'
         run: |
-          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository_owner}}/logs-viewer/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${{ needs.ci.outputs.NPM_VERSION }}
+          cosign sign -y --key /tmp/cosign.key ghcr.io/${{github.repository_owner}}/logs-viewer/sbom${{ needs.ci.outputs.IMAGE_SUFFIX }}:npm-${ORAS_DIGEST}
         env:
           COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
 
